### ISSUE TITLE
Cannot read property 'feed' of undefined

### ISSUE THREAD

**Issue by ralphtheninja** [cblgh/hyperdungeon#1]
Not sure what happens. Just making a note of it for now. @cblgh Maybe trivial for you to fix ;)

```
lms@x240 ~/src/hyperdungeon (master)
$ npm start

> hyperdungeon@0.0.0 start /home/lms/src/hyperdungeon
> node hyperdungeon.js

no such server found
starting server at hyperdungeon..
local key 371a4651e98bc3653df34553fdd701dd09c9e4c2fbfad971d0068ac4281dbf7b
12,23 > ready for connections
a new peer has joined, zarathystras's forces grow stronger
a peer has left, zarathystras's forces grow weaker
a new peer has joined, zarathystras's forces grow stronger
/home/lms/src/hyperdungeon/node_modules/hyperdb/index.js:70
        var feed = self._peersByKey[nodes[i].feed].feed
                                                  ^

TypeError: Cannot read property 'feed' of undefined
    at Feed.<anonymous> (/home/lms/src/hyperdungeon/node_modules/hyperdb/index.js:70:51)
    at emitTwo (events.js:125:13)
    at Feed.emit (events.js:213:7)
    at Feed._onextension (/home/lms/src/hyperdungeon/node_modules/hypercore-protocol/feed.js:151:13)
    at Protocol._onmessage (/home/lms/src/hyperdungeon/node_modules/hypercore-protocol/index.js:315:30)
    at Protocol._parseMessage (/home/lms/src/hyperdungeon/node_modules/hypercore-protocol/index.js:365:10)
    at Protocol._parse (/home/lms/src/hyperdungeon/node_modules/hypercore-protocol/index.js:330:37)
    at Protocol._write (/home/lms/src/hyperdungeon/node_modules/hypercore-protocol/index.js:238:8)
    at doWrite (/home/lms/src/hyperdungeon/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/lms/src/hyperdungeon/node_modules/readable-stream/lib/_stream_writable.js:395:5)
```

**Comment by ralphtheninja** [comment]
So I have two peers running on my local network. This peer keeps crashing each time I start it, so have ended up in a weird state I guess.

**Comment by cblgh** [comment]
Yeah, this has happened to me too. There's something weird that can happen with [hyperdb](https://github.com/mafintosh/hyperdb), honestly no idea atm what causes it and I'm kind of hoping @mafintosh gets it fixed during his flight this week eheh
